Repository MLH-Fellowship/volunteer-me, pull requests merged in 2020-12, with the labels that each got.

#5 Firebase-admin setup - Closes #4
  .env.local.template
  README.md
  components/AddProjectModal.js
  jsconfig.json
  lib/db.js
  lib/firebase-admin.js
  package.json
  pages/_app.js
  pages/api/hello.js
  pages/api/projects.js
  pages/dashboard.js
  pages/index.js
  utils/fetcher.js
  yarn.lock
Labels: database

#9 Backend Routes
  .prettierrc.js
  README.md
  components/AddProjectModal.js
  lib/auth.js
  package.json
  pages/_app.js
  pages/api/project/[pid].js
  pages/api/projects.js
  pages/api/user/[uid].js
  pages/api/user/createProject/[uid].js
  pages/api/users.js
  pages/api/volunteers.js
Labels: api-routes

#23 Pablo/update project form
  components/AddProjectModal.js
  components/ProjectTable.js
Labels: enhancement

#26 Updated Homepage and Footer
  components/DashboardShell.js
  components/DocsLayout.js
  components/Footer.js
  components/LoginButtons.js
  components/MDXComponents.js
  next.config.js
  package.json
  pages/_app.js
  pages/_document.js
  pages/docs.mdx
  pages/index.js
  pages/privacy.mdx
  pages/terms.mdx
  pages/volunteer-me.png
  pages/volunteer.js
  public/favicon.ico
  public/favicons/favicon.ico
  yarn.lock
Labels: frontend
